WebApp/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static


urlpatterns =[
    url('admin/', admin.site.urls),
    path('', include('calculator.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

calculator/urls.py
from django.urls import path



from . import views

"""create url(s) of the views function(s)"""
urlpatterns = [
    path('', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('calculator/', views.user_calculator, name='calculator'),
    path('history/', views.user_history, name='history'),
]

calculator/models.py
from django.db import models
from django.contrib.auth.models import User
# from django.utils import timezone


class History(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    expression = models.CharField("expression", max_length=500, blank=True)
    result = models.CharField("result", max_length=500, blank=True)


    def __str__(self):
        return self.expression



# class Profile(models.Model):
#     user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
#     first_name = models.CharField("first_name", max_length=100, blank=True)
#     last_name = models.CharField("last_name", max_length=100, blank=True)
#     password = models.CharField(max_length=100)
#     date_updated = models.DateTimeField('date_updated',default=timezone.now)
#
#
#     def __str__(self):
#         return f'{self.user.username} Profile'

WebApp/calculator/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *

from django.utils.translation import ugettext_lazy as _

from django.contrib.auth.forms import UserCreationForm,PasswordResetForm

class RegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'type': 'text', 'name': 'username', 'placeholder': 'Username'}),max_length=50, required=True)
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'type': 'text', 'name': 'first_name', 'placeholder': 'First name'}), max_length=50, required=True)
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'type': 'text', 'name': 'last_name', 'placeholder': 'Last name'}),
        max_length=50, required=True)
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password', 'name': 'password1', 'placeholder': 'Password'}),
                                max_length=100,required=True)
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password', 'name': 'password2', 'placeholder': 'Confirm Password'}),
                                max_length=100, required=True)

    class Meta:
        model = User
        fields = ['username','first_name','last_name','password1','password2']

    def clean_username(self):
        try:
            username = User.objects.get(username__iexact=self.cleaned_data['username'])
        except User.DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError(_("The username already exists."))

    def clean(self):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_("The two password fields did not match."))
        return self.cleaned_data




class LoginForm(forms.Form):
    username= forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'type': 'text', 'name': 'username', 'placeholder': 'Username'}),
        error_messages=dict(invalid="Enter a valid username"),max_length=100,required=True)
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password', 'name': 'password1', 'placeholder': 'Password'}),max_length=100, required=True)

    class Meta:
        fields = ['username','password1']

    def clean_username(self):
        try:
            username = User.objects.get(username__iexact=self.cleaned_data['username'])
        except User.DoesNotExist:
            raise forms.ValidationError(_("The username does not exist."))
        return self.cleaned_data['username']


class CalculatorForm(forms.ModelForm):
    expression = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'type': 'text', 'name': 'expression'}),max_length=300, required=True)

    class Meta:
        model = History
        fields = ['expression']


class UserUpdateForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput, max_length=100,required=True)
    last_name = forms.CharField(widget=forms.TextInput, max_length=100,required=True)
    password = forms.CharField(widget=forms.PasswordInput,max_length=100)

    class Meta:
        model = User
        fields = ['first_name', 'last_name','password']

WebApp/calculator/views.py
from django.contrib import auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.core.paginator import (Paginator,
                                   EmptyPage,
                                   PageNotAnInteger)
from .forms import *
from .models import *


def user_login(request):
    if request.method=='POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            try:
                user_username = form.cleaned_data['username']
                password = form.cleaned_data['password1']
                username = User.objects.get(username=user_username)
                user = authenticate(request,username=username,password=password)
                if user is not None:
                    login(request,user)
                    messages.success(request, f"You are now logged in as {user_username}.")
                    return redirect('calculator')
                else:
                    messages.error(request, 'Incorrect username or password.')
                    return redirect('login')

            except User.DoesNotExist:
                messages.error(request, 'Invalid credentials')
                return redirect('login')
            except Exception as e:
                print(e)
                messages.error(request, "Something went wrong. Please try again")
                return redirect('login')
    else:
        form = LoginForm()
    return render(request, 'calculator/login.html', {'form': form})


@login_required(login_url="/")
def user_logout(request):
    try:
        auth.logout(request)
        return redirect('login')
    except Exception as e:
        pass


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            try:
                username = form.cleaned_data['username']
                password = form.cleaned_data['password1']
                user = authenticate(request, username=username, password=password)
                login(request, user)
                messages.success(request, f"You are now logged in as {username}.")
                return redirect('calculator')

            except Exception as e:
                messages.error(request, 'An unexpected error occurred. Please try again.')
                return redirect('register')

    else:
        form = RegistrationForm()
    return render(request, 'calculator/register.html', {'form': form})



@login_required(login_url="/")
def profile(request):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST)
        if form.is_valid():
            try:
                password = form.cleaned_data['password']
                first_name = form.cleaned_data['first_name']
                last_name = form.cleaned_data['last_name']
                form.save(commit=False)
                u = User.objects.get(username=request.user.username)
                u.set_password(password)
                u.first_name = first_name
                u.last_name = last_name
                u.save()
                messages.success(request, f'Your account has been updated!. Please log in with your new password.')
                return redirect('profile')
            except Exception as e:
                print(e)
                messages.error(request, 'An error occurred. Please try again.')
                return redirect('profile')
    else:
        form = UserUpdateForm()
    contex = {'form': form}
    return render(request, 'calculator/profile.html', contex)



@login_required(login_url="/")
def user_calculator(request):
    if request.method == 'POST':
        form = CalculatorForm(request.POST)
        if form.is_valid():
            expression = form.cleaned_data['expression']
            hist = form.save(commit=False)
            try:
                result = eval(str(expression))
                hist.user = request.user
                hist.expression = expression
                hist.result = result
                hist.save()
                data = {'result':result}
                return render(request, 'calculator/calculator.html', data)
            except ZeroDivisionError:
                hist.user = request.user
                hist.expression = expression
                hist.result = "Undefined: dividing by zero"
                hist.save()
                messages.error(request, 'Dividing by zero is undefined')
                return redirect('calculator')
            except Exception as e:
                messages.error(request, 'Invalid expression. Please try again.')
                return redirect('calculator')

    else:
        form = CalculatorForm()
    return render(request, 'calculator/calculator.html', {'form': form})



@login_required(login_url="/")
def user_history(request):
    history_list = History.objects.filter(user=request.user).order_by('-id')
    page = request.GET.get('page', 1)

    paginator = Paginator(history_list, 10)
    try:
        history = paginator.page(page)
    except PageNotAnInteger:
        history = paginator.page(1)
    except EmptyPage:
        history = paginator.page(paginator.num_pages)

    return render(request, 'calculator/history.html', {'history': history})

calculator/views.py
from django.contrib import auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.core.paginator import (Paginator,
                                   EmptyPage,
                                   PageNotAnInteger)
from .forms import *
from .models import *


def user_login(request):
    if request.method=='POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            try:
                user_username = form.cleaned_data['username']
                password = form.cleaned_data['password1']
                username = User.objects.get(username=user_username)
                user = authenticate(request,username=username,password=password)
                if user is not None:
                    login(request,user)
                    messages.success(request, f"You are now logged in as {user_username}.")
                    return redirect('calculator')
                else:
                    messages.error(request, 'Incorrect username or password.')
                    return redirect('login')

            except User.DoesNotExist:
                messages.error(request, 'Invalid credentials')
                return redirect('login')
            except Exception as e:
                print(e)
                messages.error(request, "Something went wrong. Please try again")
                return redirect('login')
    else:
        form = LoginForm()
    return render(request, 'calculator/login.html', {'form': form})


@login_required(login_url="/")
def user_logout(request):
    try:
        auth.logout(request)
        return redirect('login')
    except Exception as e:
        pass


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            try:
                username = form.cleaned_data['username']
                password = form.cleaned_data['password1']
                user = authenticate(request, username=username, password=password)
                login(request, user)
                messages.success(request, f"You are now logged in as {username}.")
                return redirect('calculator')

            except Exception as e:
                messages.error(request, 'An unexpected error occurred. Please try again.')
                return redirect('register')

    else:
        form = RegistrationForm()
    return render(request, 'calculator/register.html', {'form': form})



@login_required(login_url="/")
def profile(request):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST,instance=request.user)
        if form.is_valid():
            try:
                password = form.cleaned_data['password']
                first_name = form.cleaned_data['first_name']
                last_name = form.cleaned_data['last_name']
                form.save(commit=False)
                u = User.objects.get(username=request.user.username)
                u.set_password(password)
                u.first_name = first_name
                u.last_name = last_name
                u.save()
                messages.success(request, f'Your account has been updated!. Please log in with your new password.')
                return redirect('profile')
            except Exception as e:
                print(e)
                messages.error(request, 'An error occurred. Please try again.')
                return redirect('profile')
    else:
        form = UserUpdateForm()
    contex = {'form': form}
    return render(request, 'calculator/profile.html', contex)



@login_required(login_url="/")
def user_calculator(request):
    if request.method == 'POST':
        form = CalculatorForm(request.POST)
        if form.is_valid():
            expression = form.cleaned_data['expression']
            hist = form.save(commit=False)
            try:
                result = eval(str(expression))
                hist.user = request.user
                hist.expression = expression
                hist.result = result
                hist.save()
                data = {'result':result}
                return render(request, 'calculator/calculator.html', data)
            except ZeroDivisionError:
                hist.user = request.user
                hist.expression = expression
                hist.result = "Undefined: dividing by zero"
                hist.save()
                messages.error(request, 'Dividing by zero is undefined')
                return redirect('calculator')
            except Exception as e:
                messages.error(request, 'Invalid expression. Please try again.')
                return redirect('calculator')

    else:
        form = CalculatorForm()
    return render(request, 'calculator/calculator.html', {'form': form})



@login_required(login_url="/")
def user_history(request):
    history_list = History.objects.filter(user=request.user).order_by('-id')
    page = request.GET.get('page', 1)

    paginator = Paginator(history_list, 10)
    try:
        history = paginator.page(page)
    except PageNotAnInteger:
        history = paginator.page(1)
    except EmptyPage:
        history = paginator.page(paginator.num_pages)

    return render(request, 'calculator/history.html', {'history': history})

calculator/templates/calculator/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %} WebCal {% endblock %}</title>
<!--    <link href="{% static 'app/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">-->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'app/css/sb-admin-2.min.css' %}" rel="stylesheet">
</head>

<body>
     <!-- Page Wrapper -->
  <div id="wrapper">
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

<!-- Main Content -->
    <div id="content">
        <!-- End of Main Content -->
            <div class="row">
                {% block content %}

                {% endblock%}
            </div>
        <!-- Footer -->
            {% include 'calculator/multiple/_footer.html' %}
        <!-- End of Footer -->
    </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'app/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'app/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'app/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'app/js/sb-admin-2.min.js' %}"></script>
    <script src="{% static 'app/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
  </div>
</body>

</html>

calculator/templates/calculator/calculator.html
{% extends 'calculator/index.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} WebCal - Calculator {% endblock %}
{% block content %}
    <section class="container bg-light" style="height:100vh;">
         <div class="row">
             <div class="content justify-content-center mt-4 ml-2 mr-2">
                <form action="{% url 'calculator' %}" method="post">
                        {% csrf_token %}
                          <div class="row">
                          <div class="col-md-6 justify-content-center">
<<<<<<< HEAD
                              <div class="text-info" style="font-weight:700;font-size:1.1rem;">
=======
                              <div class="text-dark" style="font-weight:700;font-size:1.1rem;">
>>>>>>> 8dd2c97af15c713771d9ce7e96d6b3f4210e7069
                                 Supported operations <br> are
                                 +, -, *, and / .<br>Also parenthesis <br>such as ( ) is supported.<br>
                                 For example 2+4(16/8) <br>will be entered <br>as 2+4*(16/8)<br>and
                                  the result is 10.0.<br>Division by zero is<br>undefined.
                              </div>
                          </div>
                          <div class="col-6">
                          <div class="container justify-content-center">
                          <div class="col-md-12">
                              <strong class="text-dark">Expression:</strong>
                              <div class="form-group">
                                  <input type="text" id="expression" name="expression" required size="23">
                              </div>
                            </div>
                              <div class="col-md-12 mt-1">
                                  <div class="form-group">
                                      <div class="d-flex justify-content-center">
                                        <strong class="text-dark">=</strong>
                                      </div>
                                  </div>
                              </div>
                              <div class="col-md-6">
                                  <strong class="text-dark">Result:</strong>
                                    <div class="form-group">
                                      <div class="d-flex bg-white text-dark justify-content-center border-top border-bottom border-left border-right" style="width:244px;height:35px;overflow-x:hidden;">
                                          <p style="padding:2px;">{{result|safe}}</p>
                                      </div>
                                    </div>
                              </div>
                            <div class="col-md-8 mt-3">
                                <div class="form-group">
                                    <button class="btn btn-secondary btn-lg btn-block text-white" type="submit" style="font-weight:600;font-size:14px;">Calculate</button>
                                </div>
                            </div>
                          </div>
                           </div>
                          </div>
                      </form>
             </div>
         </div>
    </section>
{% endblock %}

calculator/templates/calculator/history.html
{% extends 'calculator/index.html' %}

{% load static %}
{% block content %}
  <section class="container bg-white mt-4" style="height:100vh;">
    <div class="col-md-12">
        <div class="col-md d-flex justify-content-center">
            <div class="row" style="width:100%;">
                 <section class="container mt-2">
                     <h5 class="d-flex justify-content-center text-dark" style="font-weight:1200;">History</h5>
                  <table class="table">
                    <thead>
                    <tr>
                      <th scope="col">No.</th>
                      <th scope="col">Expression</th>
                      <th scope="col">Result</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for i in history %}
                        <tr style="font-size:12.5px;">
                          <td>{{ i.id }}</td>
                          <td class="text-dark">{{ i.expression }}</td>
                          <td>{{ i.result }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                  </table>
                     <div class="d-flex justify-content-center  mb-5">
                         {% if history.has_other_pages %}
                              <ul class="pagination mt-1 bg-white">
                                {% if history.has_previous %}
                                  <li><a href="?page={{ history.previous_page_number }}">&laquo;</a></li>
                                {% else %}
                                  <li class="disabled"><span>&laquo;</span></li>
                                {% endif %}
                                {% for x in history.paginator.page_range %}
                                  {% if history.number == x %}
                                    <li class="active"><span>{{ x }} <span class="sr-only">(current)</span></span></li>
                                  {% else %}
                                    <li><a href="?page={{ x }}">{{ x }}</a></li>
                                  {% endif %}
                                {% endfor %}
                                {% if history.has_next %}
                                  <li><a href="?page={{ history.next_page_number }}">&raquo;</a></li>
                                {% else %}
                                  <li class="disabled"><span>&raquo;</span></li>
                                {% endif %}
                              </ul>
                         {% endif %}
                     </div>
                 </section>
                </div>
        </div>
    </div>
  </section>
{% endblock %}

calculator/templates/calculator/register.html
{% extends 'calculator/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} WebCal - Signup {% endblock %}
{% block content %}
    <section class="container bg-light" style="height:100vh;">
         <div class="row justify-content-center">
             <div class="card mt-3 mb-3 bg-white justify-content-center" style="width:25rem;height:30rem;cursor:pointer;">
                 <div class="heading-1 mb-2">
                    <h4 class="d-flex justify-content-center" style="font-weight:500;">Sign Up</h4>
                 </div>
                 <div class="input mr-3 ml-3" style="font-weight:500;">
                     <div class="text-center mt-1" style="font-size:0.8rem;">
                            {% if messages  %}
                             {% for message in messages %}
                                  <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
                                    <span type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></span>
                                    <a>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error{% else %}{{ message.tags|title }}{% endif %}!</a> {{ message }}
                                  </div>
                             {% endfor %}
                           {% endif %}
                     </div>
                      <form action="{% url 'register' %}" method="post">
                        {% csrf_token %}
                          <div class="row">
                          <div class="col-md-12">
                                  <div class="form-group">
                                    <p id="username" class="">{{ form.username }}</p>
                                      {% if form.username.errors %}
                                         <div class="alert alert-danger alert-dismissible" role="alert" style="padding:1px 1px; font-size:0.8rem;">
									         <span type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></span>
                                             {{ form.username.errors }}
                                         </div>
                                      {% endif %}
                                  </div>
                            </div>
                              <div class="col-md-6">
                                  <div class="form-group">
                                    <p id="id_password1">{{ form.password1 }}</p>
                                      {% if form.password1.errors %}
                                         <div class="alert alert-danger alert-dismissible" role="alert" style="padding:1px 1px; font-size:0.8rem;">
									         <span type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></span>
                                             {{ form.password1.errors }}
                                         </div>
                                      {% endif %}
                                  </div>
                            </div>
                            <div class="col-md-6">
                                  <div class="form-group">
                                    <p id="id_password2">{{ form.password2 }}</p>
                                      {% if form.password2.errors %}
                                         <div class="alert alert-danger alert-dismissible" role="alert" style="padding:1px 1px; font-size:0.8rem;">
									         <span type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></span>
                                             {{ form.password2.errors }}
                                         </div>
                                      {% endif %}
                                  </div>
                            </div>
                            <div class="col-md-6">
                                  <div class="form-group">
                                    <p id="id_first_name" class="">{{ form.first_name }}</p>
                                      {% if form.first_name.errors %}
                                         <div class="alert alert-danger" style="font-size:0.8rem;">{{ form.first_name.errors }}</div>
                                      {% endif %}
                                  </div>
                            </div>
                            <div class="col-md-6">
                                  <div class="form-group">
                                    <p id="id_last_name" class="">{{ form.last_name }}</p>
                                      {% if form.last_name.errors %}
                                         <div class="alert alert-danger" style="font-size:0.8rem;">{{ form.last_name.errors }}</div>
                                      {% endif %}
                                  </div>
                            </div>
                            <div class="col-md-12">
                            <div class="form-group">
                                <button class="btn btn-primary btn-lg btn-block text-white" type="submit" style="font-weight:700;">Sign Up</button>
                            </div>
                          </div>
                          </div>
                      </form>
                     <div class="col-md-12 border-top pt-2">
                         <div>
                            <small class="text-muted ml-3">
                                Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Log in</a>
                            </small>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
    </section>
{% endblock %}